# SPDX-FileCopyrightText: 2026 Xiaoqiang <username_nullptr@163.com>
# SPDX-License-Identifier: MIT

set(RIWO_INSTALL_CMAKEDIR
	"${CMAKE_INSTALL_LIBDIR}/cmake/${PRO_NAME}"
	CACHE STRING "Install path for ${PRO_NAME} CMake package files."
)
set(RIWO_PACKAGE_HTTP_NEEDS_ZLIB OFF)
set(RIWO_PACKAGE_WEBSOCKET_NEEDS_ZLIB OFF)

if (NOT DEFINED RIWO_PACKAGE_OPENSSL_NEEDS_ZLIB)
	set(RIWO_PACKAGE_OPENSSL_NEEDS_ZLIB OFF)
endif ()

if (RIWO_BUILD_STATIC AND RIWO_BUILD_HTTP AND RIWO_HTTP_ZLIB_SUPPORT)
	set(RIWO_PACKAGE_HTTP_NEEDS_ZLIB ON)
endif ()

if (RIWO_BUILD_STATIC AND RIWO_BUILD_WEBSOCKET AND RIWO_WEBSOCKET_ZLIB_SUPPORT)
	set(RIWO_PACKAGE_WEBSOCKET_NEEDS_ZLIB ON)
endif ()

configure_package_config_file (
	cmake/RiwoConfig.cmake.in
	${CMAKE_CURRENT_BINARY_DIR}/RiwoConfig.cmake
	INSTALL_DESTINATION ${RIWO_INSTALL_CMAKEDIR}
)
write_basic_package_version_file (
	${CMAKE_CURRENT_BINARY_DIR}/RiwoConfigVersion.cmake
	VERSION ${PROJECT_VERSION}
	COMPATIBILITY SameMinorVersion
)
install(EXPORT RiwoTargets
	FILE RiwoTargets.cmake
	NAMESPACE Riwo::
	DESTINATION ${RIWO_INSTALL_CMAKEDIR}
)
install(FILES
	${CMAKE_CURRENT_BINARY_DIR}/RiwoConfig.cmake
	${CMAKE_CURRENT_BINARY_DIR}/RiwoConfigVersion.cmake
	DESTINATION ${RIWO_INSTALL_CMAKEDIR}
)
